version: "3.9"
services:
    client:
        build: ./client
        ports:
            - "3000:3000"
        depends_on:
            - server
    server:
        build: ./server
        ports:
            - "8080:8080"
        env_file:
            - ./server/.env
